[package]
name = "SeDebugPrivilege"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["processthreadsapi", "winuser", "memoryapi", "handleapi", "securitybaseapi", "tlhelp32", "winbase"] }
